CREATE TABLE company_user
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE patient_profile
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    old_client_guid VARCHAR(255),
    status_id       SMALLINT NOT NULL
);

CREATE TABLE patient_note
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date_time        TIMESTAMP NOT NULL,
    last_modified_date_time  TIMESTAMP NOT NULL,
    created_by_user_id       BIGINT,
    last_modified_by_user_id BIGINT,
    note                     VARCHAR(4000),
    patient_id               BIGINT    NOT NULL,
    guid                     VARCHAR(255)
);

ALTER TABLE patient_note
    ADD CONSTRAINT fk_pat_note_to_modified_user
        FOREIGN KEY (last_modified_by_user_id) REFERENCES company_user (id);

ALTER TABLE patient_note
    ADD CONSTRAINT fk_pat_note_to_created_user
        FOREIGN KEY (created_by_user_id) REFERENCES company_user (id);

ALTER TABLE patient_note
    ADD CONSTRAINT fk_pat_note_to_patient
        FOREIGN KEY (patient_id) REFERENCES patient_profile (id);
